export const Var = {
	"[##_var_google_adsense_script_url_##]": "[##_var_google_adsense_script_url_##]",
	"[##_var_dark_mode_type_##]": "[##_var_dark_mode_type_##]",
	"[##_var_side_bar_scrollbar_track_color_##]": "[##_var_side_bar_scrollbar_track_color_##]",
	"[##_var_side_bar_scrollbar_thumb_color_##]": "[##_var_side_bar_scrollbar_thumb_color_##]",
	"[##_var_post_index_item_border_color_##]": "[##_var_post_index_item_border_color_##]",
	"[##_var_post_index_item_border_active_color_##]": "[##_var_post_index_item_border_active_color_##]",
	"[##_var_background_color_at_sidebar_light_##]": "[##_var_background_color_at_sidebar_light_##]",
	"[##_var_background_color_at_sidebar_dark_##]": "[##_var_background_color_at_sidebar_dark_##]",
	"[##_var_background_color_at_blog_light_##]": "[##_var_background_color_at_blog_light_##]",
	"[##_var_background_color_at_blog_dark_##]": "[##_var_background_color_at_blog_dark_##]",
	"[##_var_background_color_at_post_index_light_##]": "[##_var_background_color_at_post_index_light_##]",
	"[##_var_background_color_at_post_index_dark_##]": "[##_var_background_color_at_post_index_dark_##]",
	"[##_var_post_youtube_horizontal_align_##]": "[##_var_post_youtube_horizontal_align_##]",
	"[##_var_is_post_codeblock_darkmode_text_color_all_white_##]": "[##_var_is_post_codeblock_darkmode_text_color_all_white_##]",
	"[##_var_is_codeblock_copy_button_show_##]": "[##_var_is_codeblock_copy_button_show_##]",
	"[##_var_darkmode_post_table_style_##]": "[##_var_darkmode_post_table_style_##]",
	"[##_var_blog_post_all_line_height_##]": "[##_var_blog_post_all_line_height_##]",
	"[##_var_codeblock_font_url_##]": "[##_var_codeblock_font_url_##]",
	"[##_var_post_image_viewer_type_##]": "[##_var_post_image_viewer_type_##]",
	"[##_var_cover_list_max_col_count_##]": "[##_var_cover_list_max_col_count_##]",
	"[##_var_cover_list_half_max_col_count_##]": "[##_var_cover_list_half_max_col_count_##]",
	"[##_var_total_list_max_col_count_##]": "[##_var_total_list_max_col_count_##]",
	"[##_var_blog_screen_max_width_##]": "[##_var_blog_screen_max_width_##]",
};