name: 'release deploy'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - run: tar -czvf ./stroke_${{ github.ref_name }}.zip ./.torytis/*

      - name: asset upload 
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: stroke_${{ github.ref_name }}.zip
          asset_name: stroke_${{ github.ref_name }}.zip
          tag: ${{ github.ref }}